Repository NiranjanaV/ShowBase, pull requests merged in 2022-03, with the labels that each got.

#59 #49 Backend Integration - Pass movie id and get movie details
  src/components/MovieDetail.js
  src/components/movieDetail.css
  src/index.js
Labels: enhancement, User Story, sprint2

#60 #49 movie detail integration style
  src/components/MovieDetail.js
  src/components/movieDetail.css
  src/index.js
Labels: sprint2

#61 #49 styling + Read genre using async await and used map function
  src/components/MovieDetail.js
  src/components/movieDetail.css
Labels: User Story, sprint2

#72 #69 backend integration,routing,styling - movie genre specific page
  src/App.js
  src/components/MovieDetail.js
  src/components/TopMovieGenre.js
  src/components/movieDetail.css
Labels: User Story, sprint 3

#92 UI Color changes
  src/components/index.css
  src/components/styles.css
Labels: bug, enhancement, sprint 3

#122 CSS Watched and CSS watchlist.
  src/components/Add.js
  src/components/BreakingBad.jpg
  src/components/GoT.jpg
  src/components/MrRobot.jpg
  src/components/UserProfile.js
  src/components/Watched.js
  src/components/Watchlist.js
  src/components/Watchlist.png
  src/components/addmovie.png
  src/components/dts.jpg
  src/components/lucifer.jpg
  src/components/manifest.jpg
  src/components/money.jpg
  src/components/peaky.jpg
  src/components/riverdale.jpg
  src/components/sherlock.jpg
  src/components/styles.css
  src/components/watch.css
  src/components/watching.jpg
  src/components/witcher.jpg
Labels: User Story, sprint 3
