Repository NiranjanaV/ShowBase, pull requests merged in 2022-04, with the labels that each got.

#136 Niranjana minorfix2
  src/App.js
  src/components/Add.js
  src/components/MovieControls.js
  src/components/ResultCard.js
  src/components/Watched.js
  src/components/Watchlist.js
  src/components/styles.css
  src/components/watch.css
Labels: bug, sprint 3

#151 Add Friends Functionality in Profile Page Part 1
  src/App.js
  src/components/ProfilePage.js
  src/components/UserProfile.js
  src/components/friends.js
  src/components/global.js
Labels: User Story, sprint4

#154 Created Profile Page for Each user
  src/components/ProfilePage.js
  src/components/UserProfile.js
Labels: User Story, sprint4

#155 Added Search Functionality for User Profile
  src/App.js
  src/components/Home.js
  src/components/SearchProfile.js
  src/components/displayProfile.js
  src/components/global.js
Labels: User Story, sprint4

#156 Created Add friend button
  src/App.js
  src/components/friends.js
Labels: User Story, sprint4

#158 Added Nav bar for movieprofile,watched,watchlist page
  src/components/MovieProfile.js
  src/components/Watched.js
  src/components/Watchlist.js
  src/components/global.js
  src/components/index.css
  src/components/styles.css
Labels: enhancement, sprint4

#161 Frontend changes/modifications
  src/App.js
  src/components/Add.js
  src/components/MovieProfile.js
  src/components/friends.js
  src/components/global.js
Labels: sprint4

#162 Display Friends Functionality, it is a new page where user can view a…
  src/components/Watched.js
  src/components/displayFriends.js
Labels: User Story, sprint4

#165 Created Pages which displays your Friends Watched and Watchlist
  cypress/integration/Account/cypresstest_account.js
  cypress/integration/Profile/cypresstest_profilepage.js
  src/components/FriendsWatched.js
  src/components/FriendsWatchlist.js
Labels: User Story, sprint4

#166 Added Search bar button in movies and shows page linked to Add movies page
  src/components/MovieProfile.js
  src/components/Result.js
Labels: enhancement, sprint4

#174 Added Navigation bar and Footer for all the pages
  src/components/Add.js
  src/components/Login.js
  src/components/MovieDetail.js
  src/components/MovieProfile.js
  src/components/Watched.js
  src/components/Watchlist.js
  src/components/global.js
  src/components/login.css
  src/components/movieDetail.css
  src/components/styles.css
Labels: enhancement, good first issue, sprint4

#177 Minor Fix from last commmit
  src/components/Home.js
  src/components/MovieProfile.js
  src/components/movieDetail.css
  src/components/styles.css
Labels: bug

#179 Added session to Profile Page, Add Friends Page, Display Friends Page
  src/App.js
  src/components/ResultCard.js
  src/components/displayFriends.js
  src/components/friends.js
Labels: enhancement, sprint4

#183 Integration of MovieDetail Page with Add page
  src/components/Add.js
  src/components/MovieAdd.js
  src/components/styles.css
Labels: User Story, sprint4

#184 Fixed footer alignment issues CSS
  src/components/Home.js
  src/components/Login.js
  src/components/MovieProfile.js
  src/components/Watched.js
  src/components/Watchlist.js
  src/components/login.css
  src/components/styles.css
Labels: bug, sprint4

#187 Cypress testing for all the pages and functionalities in the website
  cypress/integration/Account/cypresstest_account.js
  cypress/integration/Home/cypresstest.js
  cypress/integration/MoviesandShows/cypresstest_moviesnshows.js
  cypress/integration/Profile/cypresstest_profilepage.js
  src/components/MovieAdd.js
Labels: User Story, sprint4

#189 Cypress testing minor fix update
  cypress/integration/Account/cypresstest_account.js
  src/components/global.js
Labels: enhancement, sprint4
